### ISSUE TITLE
For long songs only the first 10 seconds are being decoded

### ISSUE THREAD

**Issue by Haselnussmann** [JorenSix/RubberBandJNI#2]
After 10 seconds (or something similar, depending on the set speed) the audio player stops playing and the thread seems to freeze. Probably there is an issue with the JNI stuff... Would be nice if you could fix this or tell be how to correct it :)

**Comment by Haselnussmann** [comment]
Btw, I'm using Windows 64x if that is important.

**Comment by JorenSix** [comment]
Hi

I have not been able to replicate the issue. Comment here if your probem is still occuring.

**Comment by fwaveVT** [comment]
I also notice this when I compile the example on a Windows x64 machine. The pipe decoder plays for about 10 seconds and then stops. I have substituted the fromPipe with fromFile in RubberBandFrame and the playback is fine (but then I have to be sure the file is mono wav 44100 PCM). Strangely, the same example when compiled on a macOS does not have this behavior.
