### ISSUE TITLE
Getting error while executing ndk-build

### ISSUE THREAD

**Issue by prashant2018** [JorenSix/RubberBandJNI#3]
Hi I am getting this error : 
[armeabi-v7a] Compile++      : rubberband <= RubberBandStretcherJNI.cpp
clang++: error: unknown argument: '-ftree-vect-loop-version'
make: *** [/home/prashant/breakfastquay-rubberband-46805fcedf7e/obj/local/arm64-v8a/objs/rubberband//home/prashant/breakfastquay-rubberband-46805fcedf7e/src/jni/RubberBandStretcherJNI.o] Error 1

**Comment by tburt** [comment]
Hi, I'm having this same problem - is there a known solution?

**Comment by sbodder** [comment]
Having the same issue

**Comment by tburt** [comment]
I ended up using the android project here to build the libraries: https://github.com/koendv/rubberband then importing them manually to my project

**Comment by sbodder** [comment]
Hey tburt thanks for the response,  appreciate it!  Will give that a try.

Btw what ndk version did you use to build it?

Shane

Sent from BlueMail<http://www.bluemail.me/r?b=14063>
On 15 Nov 2018, at 12:34, tburt <notifications@github.com<mailto:notifications@github.com>> wrote:

I ended up using the android project here to build the libraries: https://github.com/koendv/rubberband then importing them manually to my project

**Comment by tburt** [comment]
I honestly can't remember what version I used... I'm not massively experienced with using ndk. But I seem to remember that I didn't have any problems building using that other github project. I'd give that a go first, using whatever version it has set in the project.

**Comment by sbodder** [comment]
Ok cheers 👍

Sent from BlueMail<http://www.bluemail.me/r?b=14063>
On 15 Nov 2018, at 14:50, tburt <notifications@github.com<mailto:notifications@github.com>> wrote:

I honestly can't remember what version I used... I'm not massively experienced with using ndk. But I seem to remember that I didn't have any problems building using that other github project. I'd give that a go first, using whatever version it has set in the project.
