### ISSUE TITLE
Audio quality issue when time ratio or pitch scale != to 1.0

### ISSUE THREAD

**Issue by fwaveVT** [JorenSix/RubberBandJNI#4]
I have compiled the Rubber Band example under both macOS (MacBook OSX 10.2.3 )and Windows 10 (x64 machine) using JDK 1.8.0_121 and find that as soon as I change either the time stretching or pitch shifting values, there is a noticeable distortion in the output. It sounds somewhat like clipping and is pronounced on percussive transients such as the kick and snare drums beats. When the player starts (e.g. no change in values), the quality is perfect.
My source audio is mono WAV at 44100 sample rates, though I have tried other formats. I have also experimented with different buffer sizes in the AudioProcessor and AudioDispatcherFactory. I'm wondering if there might be an error in the buffer sizing that could cause some truncation resulting in the distortion I hear? Any suggestions would be greatly appreciated. I would love to use TarsosDSP with Rubber Band, but will need solid (and stereo) audio quality. Thanks!

**Comment by JorenSix** [comment]
Hi,

Clipping can indeed occur when input that is already near the clipping limit is time-stretched. One simple solution is to make the sound half as loud before calling the rubberband audio processor which gives the timestretcher some headroom. 

In its current design TarsosDSP aims to be as simple as possible to demonstrate audio processing algorithms and feature extractors while also being capable enough to get some real work done. One of the simplifications is only single channel support. 

Stereo support would entail a serious refactoring of TarsosDSP's processing pipeline. Nothing too complicated but quite a bit of work. 

You could also directly use the RubberBandJNI code  without TarsosDSP and do input and output using the standard java libraries.

Good luck!

Joren
